version: '3.3'

services:
  bot:
    container_name: "tgbot"
    build: .
    restart: always
    env_file:
      - ".env"
  
  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2001
    volumes:
      - ./data:/var/lib/postgresql/data
